name: Deploy Client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains('refs/heads/staging refs/heads/master', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: move deploy script
        run: mv deploy.sh build/
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: contains('refs/heads/staging refs/heads/master', github.ref)
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: build-artifact
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: |
          chmod +x deploy.sh
          ./deploy.sh deploy_s3
        working-directory: build-artifact
      - name: Invalidate Cache 
        run: ./deploy.sh clearCache
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        working-directory: build-artifact
